version: "3.8"
services: 
  api:
    build: ./server
    container_name: api_c
    ports:
      - '5050:5050'
    volumes:
      - ./server:/app
      - /app/node_modules
  pancakeswap:
    build: ./pancake-swapp-react
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./pancake-swapp-react:/app
      - /app/node_modules
    stdin_open: true
    tty: true