const db = [
  {
    id: 1,
    name: "3D BRAVE TIGERS",
    volume: 127500,
    itemCount: 55,
    banner: "3d_Brave_Tigers.jpg",
    avatar: "3d_Brave_Tigers.jpg",
  },
  {
    id: 2,
    name: "ALPIES",
    volume: 103230,
    itemCount: 27,
    banner: "Alpies.jpg",
    avatar: "Alpies.jpg",
  },
  {
    id: 3,
    name: "CARTEL PUNKS",
    volume: 97527,
    itemCount: 255,
    banner: "Cartel_Punks.jpg",
    avatar: "Cartel_Punks.jpg",
  },
  {
    id: 4,
    name: "CUCTI CLUB",
    volume: 10259,
    itemCount: 777,
    banner: "Cucti_Club.jpg",
    avatar: "Cucti_Club.jpg",
  },
  {
    id: 5,
    name: "HI-FI",
    volume: 5327,
    itemCount: 1300,
    banner: "Hi-Fi.jpg",
    avatar: "Hi-Fi.jpg",
  },
  {
    id: 6,
    name: "HORROR APES",
    volume: 324985,
    itemCount: 7777,
    banner: "Horror_Apes.jpg",
    avatar: "Horror_Apes.jpg",
  },
  {
    id: 7,
    name: "KITTENS",
    volume: 532,
    itemCount: 555,
    banner: "Kittens.jpg",
    avatar: "Kittens.jpg",
  },
  {
    id: 8,
    name: "MONSTA PARTY",
    volume: 27355,
    itemCount: 999,
    banner: "Monsta_Party.jpg",
    avatar: "Monsta_Party.jpg",
  },
  {
    id: 9,
    name: "MOON PETS",
    volume: 355418,
    itemCount: 1500,
    banner: "Moon_Pets.jpg",
    avatar: "Moon_Pets.jpg",
  },
  {
    id: 10,
    name: "NEURAL PEPE",
    volume: 12355,
    itemCount: 777,
    banner: "Neural_Pepe.jpg",
    avatar: "Neural_Pepe.jpg",
  },
  {
    id: 11,
    name: "PANCAKE SQUAD",
    volume: 427730,
    itemCount: 333,
    banner: "Pancake_Squad.jpg",
    avatar: "Pancake_Squad.jpg",
  },
  {
    id: 12,
    name: "POOPIES",
    volume: 124,
    itemCount: 10000,
    banner: "Poopies.jpg",
    avatar: "Poopies.jpg",
  },
  {
    id: 13,
    name: "RAR3 MUSHROOMS",
    volume: 4250,
    itemCount: 150,
    banner: "rar3_Mushrooms.jpg",
    avatar: "rar3_Mushrooms.jpg",
  },
  {
    id: 14,
    name: "TRAPPY TRUNKZ",
    volume: 212683,
    itemCount: 1299,
    banner: "Trappy_Trunkz.jpg",
    avatar: "Trappy_Trunkz.jpg",
  },
  {
    id: 15,
    name: "WOLFANGERS",
    volume: 7516,
    itemCount: 499,
    banner: "Wolfangers.jpg",
    avatar: "Wolfangers.jpg",
  },
];

module.exports = { db };
